### ISSUE TITLE
Does not work with non-default VPC

### ISSUE THREAD

**Issue by mtslzr** [ferulisses/aws-manage-firewall-action#1]
Head's up: since you are passing `group-name` with the CLI command, it defaults to EC2 Classic and only checks the default VPC. Should probably update the options to take a SG ID, which would work as intended.

Can see the explanation here: https://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-ingress.html

Would recommend using `group-id` instead, or as an option.

**Comment by ferulisses** [comment]
Thanks for your suggestion, I read the documentation and you are correct, group-id is more compatible with other configurations. 

I made a new release changing the parameter as you suggested.

This new release also auto remove the firewall rule at the end, so, even with a new parameter, there is a few lines at the script.
